Make first rc (WIP)
umbrellio/verifly pull request #1
Opened 2017-03-29 08:49 UTC by JelF

WIP

2017-03-29 18:33 UTC, akxcv commented
I think you should configure Travis to only build the pull request once (e.x. only build pushes to "master" branch and PRs).

2017-03-30 05:54 UTC, JelF commented
@akxcv travis made exactly one build when i pushed this branch

2017-03-30 12:23 UTC, akxcv commented
@JelF and it made another one when you created this pull request.

2017-03-31 07:53 UTC, JelF commented
@akxcv done

2017-03-31 08:05 UTC, JelF commented
ill prefer to finalize work on this point and then add changes via separate PR's @akxcv, could you review entire repository in this PR?

2017-03-31 11:12 UTC, akxcv requested changes
Overall looks good! 👍

2017-03-31 11:12 UTC, akxcv commented on .rubocop.yml
>    # REVIEW: why is that dangerous?
Not sure about the dangers, but I think that `some_method(a) { |val| puts val }` is more readable than `some_method a { |val| puts val }`.

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +  # Applicates objects called `applicable`
"Applies "applicable" objects to given bindings" or smth like that

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +  # (all objects are applicable, this typing made for usage purposes).
"this naming(?) *is chosen* for usage(convenience?) purposes"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +  # This class uses ClassBuilder subsystem, start with .call method
Maybe just "system", not "subsystem"?
Also, "When reading the code, we suggest starting from '.call' method"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # Proxy is used when applicable itself is an Applicator.
"when applicable is itself an instance of Applicator" sounds clearer

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # It just delegates #call to it
"It simply delegates "#call" method to the applicable."

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +      # @return Proxy if applicable is Applicator
"is an instance of Applicator"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +      # @param binding_ [#instance_exec] target to applicate applicable
"target to apply the applicable to"
It's beginning to sound weird, but that's just a consequence of naming.

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +      # @param context additional info to send it to applicable
"to send to the applicable", you don't need the "it" here

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # MethodExtractor is used when applicable is a symbol.
"the applicable"
Also, "Symbol"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # It extracts extracts method from binding_ and executes it on binding_
"It extracts a method from binding_ and then executes it in its context" or smth

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +      # @param binding_ [#instance_exec] target to applicate applicable
Same as earlier

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +      # @return [String, Integer] file and line where `Applicator.call` called
"was called", or "is called", or "is being called"... Depending on what you actually meant

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # Quoter is used when there is no other way to applicate applicatable.
Here and everywhere else, change "applicate" to "apply".

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # Applicates applicable on binding_ with context
And "applicates" to "applies".

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    #   see examples in sublcasses defenitions
"in subclass definitions"
Or, "in definitions of subclasses"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    #   If applicable would not accept params, it would not be sent
"If applicable cannot accept params, the data will not be sent"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    #   @param binding_ [#instance_exec] biding would be used in application
"binding to be used for application"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    #   @param context param would be passed if requested
"param that will be passed if requested"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # invokes lambda basing on it's arity
"based on its arity"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator.rb
> +    # @return invokation result
"invocation"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator_with_options.rb
> +  # An applicator with usefull options
useful

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator_with_options.rb
> +  #   main action only applicate if this applicates to truthy value
"...only applies if this evaluates..."

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/applicator_with_options.rb
> +    # @return [nil] if conditions check failed
condition checks

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +  # inverted dependencies. It means, that child classes are
dependency injection / dependency inversion?

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +  # deciding to be or not to be used
"It means that child classes decide whether they should be built or not"

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +  #   klasses to iterate during search of most suitable
classes

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +    #   Array of classes which would be checked if they
will

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +    #   suite constructor arguments. Order maters
matters

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/class_builder.rb
> +      # Default implementation if build_class. Feel free to change
of

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier.rb
>    #   Array to collect all messages yielded by verifier
Array with all messages yielded by the verifier

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    # Builds ApplicatorWithOptions from different invokation styles.
invocation

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   array of arguments invoked with
an array of arguments to invoke methods with ?

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   block invoked with
-||-

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +      # Tries different invokation styles untill one matches
invocation; until

2017-03-31 11:12 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +          Nested verifiers should inherit verifier they nested in
"...should inherit from the verifier they are nested in"

2017-03-31 11:12 UTC, akxcv commented on spec/xverifier/applicator_spec.rb
> +    Class.new { define_method(:foo) { |*| } }
What on Earth is this magic?

2017-03-31 11:12 UTC, akxcv commented on spec/xverifier/class_builder_spec.rb
> +  let(:unbuildabe) { class_double(klass, build_class: nil) }
unbuildable

2017-03-31 11:12 UTC, akxcv commented on spec/xverifier_spec.rb
> +end
❤️

2017-03-31 16:18 UTC, JelF commented on .rubocop.yml
>    # REVIEW: why is that dangerous?
It is about following syntax:
```
spec/xverifier/verifier_spec.rb:55:9: W: Parenthesize the param lambda to make sure that the block will be associated with the verify method call.
        verifier.verify ->(context) { message!(context) }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2017-03-31 16:19 UTC, JelF commented on lib/xverifier/applicator.rb
> +      # @return [String, Integer] file and line where `Applicator.call` called
i also forgot to make a spec for this

2017-03-31 16:20 UTC, JelF commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   block invoked with
???

2017-03-31 18:43 UTC, akxcv commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   block invoked with
I meant "same as above".
"a block to invoke methods with"

2017-03-31 18:45 UTC, akxcv commented on .rubocop.yml
>    # REVIEW: why is that dangerous?
It wants you to put parens around the lambda...
Yeah, I guess we can do without this rule.

2017-04-03 07:57 UTC, JelF commented on lib/xverifier/applicator.rb
> +    # invokes lambda basing on it's arity
Doesn't it mean like "select some lambda"
Used: "invokes lambda respecting it's arity"

2017-04-03 07:58 UTC, JelF commented on lib/xverifier/applicator_with_options.rb
> +  #   main action only applicate if this applicates to truthy value
evaluates is more generic and does not describe, that this stuff would be applicated

2017-04-03 08:09 UTC, JelF commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   array of arguments invoked with
it changes sence, but should be okish

2017-04-03 08:10 UTC, JelF commented on lib/xverifier/verifier/applicator_with_options_builder.rb
> +    #   array of arguments invoked with
well, not in this place. I'll try to reword:
array of arguments `Verifier.verify` invoked with

2017-04-03 09:55 UTC, JelF commented
@akxcv can you re-check it?

2017-04-03 10:39 UTC, akxcv reviewed
Alright, let's correct this one line and then I'll make a pull request with grammar corrections for the README (eventually, if I find any mistakes).

2017-04-03 10:39 UTC, akxcv commented on .rubocop.yml
> +  # Spies are not always usable, i.e. we wanna to stub something we haven't create
1) "wanna" = "want to"
2) "... haven't created"

2017-04-03 11:08 UTC, akxcv approved these changes

2017-04-03 11:11 UTC, merged