Improve grammar and wording
umbrellio/verifly pull request #7
Opened 2017-04-05 06:27 UTC by akxcv

2017-04-05 07:00 UTC, JelF requested changes
Please, run `$ bin/rake` before each commit or at least each push

2017-04-05 07:00 UTC, JelF commented on lib/verifly/class_builder.rb
> +  # I find it much more object-oriented
i like OOPish, but up to you

2017-04-05 07:00 UTC, JelF commented on lib/verifly/verifier.rb
> +    #   implementation example: `super { Message.new(status, text, description) }`
it should not be just an example, it should someway force

2017-04-05 07:00 UTC, JelF commented on lib/verifly/verifier/applicator_with_options_builder.rb
> +    #   array of arguments to invoke Verifier.verify with
It is already invoked, isnt it?

2017-04-05 07:00 UTC, JelF commented on lib/verifly/version.rb
> +  # * c stands for patch changes (not touching public or private api)
I think patch should be reworded to incremental or something like this

2017-04-05 08:05 UTC, akxcv commented on lib/verifly/class_builder.rb
> +  # I find it much more object-oriented
"object-oriented" feels much better to me

2017-04-05 08:06 UTC, akxcv commented on lib/verifly/verifier.rb
> +    #   implementation example: `super { Message.new(status, text, description) }`
What exactly should be forced?

2017-04-05 08:07 UTC, akxcv commented on lib/verifly/version.rb
> +  # * c stands for patch changes (not touching public or private api)
According to semver.org, it's called "patch" version.

2017-04-07 13:21 UTC, akxcv commented
@JelF everything should be resolved now.

2017-04-07 14:25 UTC, JelF approved these changes

2017-04-07 14:26 UTC, merged